#!/bin/bash

# This file is automatically generated by generate_runscripts.sh.
WORKDIR=/cluster/home/ggurung/DMG4-MiniBooNEBD/build/scripts/runs

$WORKDIR/../../Brem -m $WORKDIR/../../batch.mac -o ebrem62.root -s 62
